### ISSUE TITLE
Boutons de gestion de serveurs

### ISSUE THREAD

**Issue by Zuka-a** [Gugustinette/discord-custom-theme#1]
.circleIconButton-1VxDrg {
  background-color: rgb(var(--bg-overlay-color-inverse)/var(--bg-overlay-opacity-6)) !important;
}

**Comment by Gugustinette** [comment]
Effectivement ça a l'air de marcher, en revanche bizarre qu'il y ait un identifiant dessus nan ? 

Si ça marche de mon côté ET du tient, ça doit pas être mal, mais ça se trouve c'est un identifiant qui peut changer en fonction des versions de Discord ? Je sais pas trop

**Comment by Zuka-a** [comment]
Ça me parrait bizarre aussi. J'ai essayé d'utiliser la var mais ça ne fonctionnait pas (var(--background-primary))

**Comment by Gugustinette** [comment]
Ok je vois, et tu penses qu'on pourrait fix les intégrations nous même du coup ?

**Comment by Gugustinette** [comment]
J'ai push les modifications (+ Intégrations et ombres blanches chelou, je ferme l'Issue)
